/**
 * Template Data Schemas
 *
 * Defines available data fields for different template types
 */

import type { DataSchema, DataField } from '@/types/template-designer';

// ============================================================================
// INVOICE TEMPLATE DATA SCHEMA
// ============================================================================

export const INVOICE_DATA_SCHEMA: DataSchema = {
  templateType: 'invoice',
  fields: [
    {
      name: 'invoice',
      label: 'Invoice',
      type: 'object',
      children: [
        { name: 'invoiceNumber', label: 'Invoice Number', type: 'string', example: 'INV-2025-001' },
        { name: 'date', label: 'Invoice Date', type: 'date', example: '2025-12-01' },
        { name: 'dueDate', label: 'Due Date', type: 'date', example: '2025-12-31' },
        { name: 'total', label: 'Total Amount', type: 'number', example: 15000.00 },
        { name: 'subtotal', label: 'Subtotal', type: 'number', example: 14500.00 },
        { name: 'tax', label: 'Tax', type: 'number', example: 500.00 },
      ],
    },
    {
      name: 'project',
      label: 'Project',
      type: 'object',
      children: [
        { name: 'projectName', label: 'Project Name', type: 'string', example: '2023 AAPR - CA' },
        { name: 'poNumber', label: 'PO Number', type: 'string', example: 'PO-00133385' },
        { name: 'projectManager', label: 'Project Manager', type: 'string', example: 'John Smith' },
      ],
    },
    {
      name: 'company',
      label: 'Company',
      type: 'object',
      children: [
        { name: 'companyName', label: 'Company Name', type: 'string', example: 'CTI' },
        { name: 'address', label: 'Address', type: 'string', example: '123 Main St' },
        { name: 'phone', label: 'Phone', type: 'string', example: '(555) 123-4567' },
      ],
    },
    {
      name: 'items',
      label: 'Invoice Items',
      type: 'array',
      children: [
        { name: 'description', label: 'Description', type: 'string', example: 'Consulting Services' },
        { name: 'quantity', label: 'Quantity', type: 'number', example: 40 },
        { name: 'rate', label: 'Rate', type: 'number', example: 150.00 },
        { name: 'amount', label: 'Amount', type: 'number', example: 6000.00 },
      ],
    },
  ],
};

// ============================================================================
// REPORT TEMPLATE DATA SCHEMA
// ============================================================================

export const REPORT_DATA_SCHEMA: DataSchema = {
  templateType: 'report',
  fields: [
    {
      name: 'department',
      label: 'Department',
      type: 'object',
      children: [
        { name: 'departmentName', label: 'Department Name', type: 'string', example: 'Infrastructure' },
        { name: 'departmentCode', label: 'Department Code', type: 'string', example: '300' },
      ],
    },
    {
      name: 'contract',
      label: 'Contract',
      type: 'object',
      children: [
        { name: 'contractNumber', label: 'Contract Number', type: 'string', example: '202262947' },
        { name: 'contractName', label: 'Contract Name', type: 'string', example: 'IPMSS Infrastructure' },
      ],
    },
    {
      name: 'report',
      label: 'Report Info',
      type: 'object',
      children: [
        { name: 'reportDate', label: 'Report Date', type: 'date', example: '2025-12-01' },
        { name: 'generatedBy', label: 'Generated By', type: 'string', example: 'Admin User' },
        { name: 'reportingPeriod', label: 'Reporting Period', type: 'string', example: 'November 2025' },
      ],
    },
    {
      name: 'projects',
      label: 'Projects',
      type: 'array',
      children: [
        { name: 'poNumber', label: 'PO Number', type: 'string', example: 'PO-00133385' },
        { name: 'projectName', label: 'Project Name', type: 'string', example: '2023 AAPR - CA' },
        { name: 'budget', label: 'Budget', type: 'number', example: 25000.00 },
        { name: 'invoiced', label: 'Invoiced', type: 'number', example: 20000.00 },
        { name: 'remaining', label: 'Remaining', type: 'number', example: 5000.00 },
      ],
    },
    {
      name: 'totals',
      label: 'Totals',
      type: 'object',
      children: [
        { name: 'totalBudget', label: 'Total Budget', type: 'number', example: 500000.00 },
        { name: 'totalInvoiced', label: 'Total Invoiced', type: 'number', example: 450000.00 },
        { name: 'totalRemaining', label: 'Total Remaining', type: 'number', example: 50000.00 },
      ],
    },
  ],
};

// ============================================================================
// COVER PAGE TEMPLATE DATA SCHEMA
// ============================================================================

export const COVER_PAGE_DATA_SCHEMA: DataSchema = {
  templateType: 'cover-page',
  fields: [
    {
      name: 'document',
      label: 'Document',
      type: 'object',
      children: [
        { name: 'title', label: 'Document Title', type: 'string', example: 'Monthly Invoice Package' },
        { name: 'subtitle', label: 'Subtitle', type: 'string', example: 'Infrastructure Department' },
        { name: 'date', label: 'Document Date', type: 'date', example: '2025-12-01' },
      ],
    },
    {
      name: 'company',
      label: 'Company',
      type: 'object',
      children: [
        { name: 'companyName', label: 'Company Name', type: 'string', example: 'CTI' },
        { name: 'address', label: 'Address', type: 'string', example: '123 Main St' },
        { name: 'phone', label: 'Phone', type: 'string', example: '(555) 123-4567' },
      ],
    },
    {
      name: 'recipient',
      label: 'Recipient',
      type: 'object',
      children: [
        { name: 'recipientName', label: 'Recipient Name', type: 'string', example: 'John Doe' },
        { name: 'recipientTitle', label: 'Recipient Title', type: 'string', example: 'Project Manager' },
        { name: 'recipientCompany', label: 'Recipient Company', type: 'string', example: 'Client Corp' },
      ],
    },
  ],
};

// ============================================================================
// CUSTOM TEMPLATE DATA SCHEMA
// ============================================================================

export const CUSTOM_DATA_SCHEMA: DataSchema = {
  templateType: 'custom',
  fields: [
    {
      name: 'text',
      label: 'Simple Text',
      type: 'string',
      example: 'Any text value',
    },
    {
      name: 'number',
      label: 'Number',
      type: 'number',
      example: 12345,
    },
    {
      name: 'date',
      label: 'Date',
      type: 'date',
      example: '2025-12-01',
    },
  ],
};

// ============================================================================
// SCHEMA REGISTRY
// ============================================================================

export const DATA_SCHEMAS: Record<string, DataSchema> = {
  invoice: INVOICE_DATA_SCHEMA,
  report: REPORT_DATA_SCHEMA,
  'cover-page': COVER_PAGE_DATA_SCHEMA,
  custom: CUSTOM_DATA_SCHEMA,
};

export function getDataSchema(templateType: string): DataSchema {
  return DATA_SCHEMAS[templateType] || CUSTOM_DATA_SCHEMA;
}

// ============================================================================
// SAMPLE DATA GENERATOR
// ============================================================================

export function generateSampleData(templateType: string): Record<string, any> {
  const schema = getDataSchema(templateType);

  function generateFieldValue(field: DataField): any {
    if (field.example !== undefined) {
      return field.example;
    }

    switch (field.type) {
      case 'string':
        return `Sample ${field.label}`;
      case 'number':
        return 0;
      case 'date':
        return new Date().toISOString();
      case 'boolean':
        return false;
      case 'array':
        return field.children ? [generateFieldObject(field.children)] : [];
      case 'object':
        return field.children ? generateFieldObject(field.children) : {};
      default:
        return null;
    }
  }

  function generateFieldObject(fields: DataField[]): Record<string, any> {
    const obj: Record<string, any> = {};
    fields.forEach(field => {
      obj[field.name] = generateFieldValue(field);
    });
    return obj;
  }

  return generateFieldObject(schema.fields);
}
